### ISSUE TITLE
What is the exact markup language used for the docs?

### ISSUE THREAD

**Issue by dandv** [webix-hub/docs#6]
It seems to be a Markdown flavor, but which one? https://github.com/webix-hub/docs/pull/3#issuecomment-69743426 mentions a custom language. It would be great to have it documented. In particular,

1. How can we mark inline code? Backticks? #5 suggests not.
2. Do tables formatted with | work?

**Comment by Zwillinge** [comment]
1. Actually, backticks can be used to mark inline code but not in that case (within an HTML table). That's a good issue to fix.
2. Tables formatted with | work. 

I suppose we will document the markdown differences in the near future so that the contributors can format the docs correctly.

**Comment by dandv** [comment]
How is the `{{memo ...}}` tag rendered?

https://github.com/webix-hub/docs/blob/master/data/api/refs/ui.tree.md contains it but http://docs.webix.com/api__refs__ui.tree.html doesn't show anything special around the "A hierarchical structure of nodes." text.

**Comment by Zwillinge** [comment]
Since API reference structure is generated automatically, {{memo }} is taken as short description of a class in the http://docs.webix.com/api__toc__ui.html page. 

At the same time, all "refs" pages are auto-generated. The right place to change memo and the rest of the text is here: https://github.com/webix-hub/docs/blob/master/data/api/obj/ui.tree.md
